title: Sensor Data Exchange
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-sensor-data-exchange
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://sdx.sensors.gov.sg/sdx/home
google_analytics: null

fast_build: false
offline: false
preload_pages: true

styling_options:
  primary_brand_color: "#00B4B4"
  logo_path: /assets/sdx-logo.png
  opendoc_logo_path: /assets/sdx-logo.png
  feedback_url: https://form.gov.sg/5e4e552386290e0013ae5685
  logo_url: https://sdx.sensors.gov.sg/sdx/home

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

document_order:
 - User Guide
 - FAQs
 - Terms of Use
 - Privacy Statement

folders:
  - name: /User%20Guide
    title: Sensor Data Exchange
    subtitle: User Guide
    order:
      - Introduction
      - Getting Started
      - Home Page
      - Browse Topic
      - Projects
      - My Subscribers
      - My Subscriptions
      - Glossary
