title: Sensor Data Exchange
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-sensor-data-exchange
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://sdx.sensors.gov.sg/sdx/home
#server_DEV: https://search-staging.opendoc.sg
google_analytics:  #----> Optional, Google analytics ID

fast_build: false
offline: false
preload_pages: true

styling_options:
  primary_brand_color: '#00B4B4'  #----> Optional, theme color
  logo_path: /assets/sdx-logo.png  #----> Optional, path to logo
  opendoc_logo_path: /assets/sdx-logo.png
  feedback_url: https://form.gov.sg/5e4e552386290e0013ae5685 #----> Optional, feedback url

hide_toolbar:
  sidebar: false
  pdf: false
  github: true

folders:
  - name: '/User%20Guide'
    title: 'Sensor Data Exchange User Guide'
    subtitle: ''
    order:
      - "Introduction.md"
      - "Getting Started.md"
      - "Home Page.md"
      - "Browse Topic.md"
      - "Projects.md"
      - "My Subscribers.md"
      - "My Subscriptions.md"
      - "Glossary.md"
