title: Sensor Data Exchange
remote_theme: opendocsg/opendoc-theme@master
timezone: Asia/Singapore
repository: opendocsg/opendoc-sensor-data-exchange
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: https://sdx.sensors.gov.sg
server_DEV: https://staging.dbm8xnuhpkaq9.amplifyapp.com
google_analytics:  #----> Optional, Google analytics ID

fast_build: false
offline: false
preload_pages: true

styling_options:
  primary_brand_color: '#444'  #----> Optional, theme color
  logo_path: /assets/default/images/sdx-logo.svg  #----> Optional, path to logo
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/5e4e552386290e0013ae5685 #----> Optional, feedback url
